from building import *

#src   = Glob('*.c')
#group = DefineGroup('libc_test', src, depend = ['RT_USING_NEWLIB', 'RT_USING_PTHREADS'])

src = []

if GetDepend('RT_USING_EXAMPLES_LIBC_TERMIOS'):
    src += ['termios_test.c']

group = DefineGroup('libc_test', src, depend = ['RT_USING_EXAMPLES_LIBC', 'RT_USING_PTHREADS'])

Return('group')
